version: "3"

services:
  openpose-test:
    build: .
    network_mode: host
    ipc: host
    tty: true
    volumes:
      - ./workspace:/root/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
    # devices:
    #   - /dev:/dev
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
              - gpu
