version: "3"

services:
  openpose-test:
    build: .
    network_mode: host
    ipc: host
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./openpose:/root/workspace/openpose
      - ./test:/root/workspace/test
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
    # devices:
    #   - /dev:/dev
    # privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
              - gpu
